id: 71c7263fa6304176898372634637be24
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_151-The_Questions_of_Pratibhanamati-v2
  language: en
  author: ''
  volume: {}
